### ISSUE TITLE
Use aria2c

### ISSUE THREAD

**Issue by Pevernow** [SonOfLysander/git-openssl-shellscript#12]
#idea
Why not use aria2c?
It can make download speed up.
In some countries(such as China),limited access to foreign networks 's speed.
I think that can help them to install git with openssl quickly.

**Comment by nikole-dunixi** [comment]
I used curl because I'm (and many others) are familiar with it. But I'm open to see any improvement, especially if it helps Chinese citizens from within the great wall. Do you have a fork/pull request showing how you'd like to see `aria2c` used optimally?

**Comment by Pevernow** [comment]
I think it can run very well all over the world.(including China)
In some countries，access to foreign network is slow.
Single-threaded download speed only 30 KB/s.
But using multi-threaded download speed is improved greatly.
Use multi-threaded better than using single-threaded.

**Comment by nikole-dunixi** [comment]
If you have a pull request with the changes you'd like to see, I'll be happy to review it 😁

**Comment by Pevernow** [comment]
No problem.
But I  have no time to have the pull request this week.
I would like to have the pull request next week.

**Comment by nikole-dunixi** [comment]
Closing for the time being, I don't currently have the bandwidth to try this but when your PR comes through I'll gladly take a look!
