### ISSUE TITLE
gzip: stdin: not in gzip format

### ISSUE THREAD

**Issue by mshojatalab** [SonOfLysander/git-openssl-shellscript#16]
I get this when I run the script:

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

I'm on Ubuntu 20.04.2 LTS

**Comment by jonny-green** [comment]
The pull request #15 should fix this, the the links in the Github html must have changed recently. It's an easy fix, hopefully the PR will be accepted soon
