### ISSUE TITLE
unmet dependencies

### ISSUE THREAD

**Issue by vitaly-zdanevich** [SonOfLysander/git-openssl-shellscript#7]
`The following packages have unmet dependencies:
 dpkg-dev : Depends: libdpkg-perl (= 1.17.5ubuntu5.7) but 1.18.18 is to be installed
E: Unable to correct problems, you have held broken packages.`

Ubuntu 14.04 with all updates.

**Comment by nikole-dunixi** [comment]
Can you be more specific I need more information to replicate it? Ubuntu server? 32 or 64 bit, where and how are you using it, etc?

**Comment by vitaly-zdanevich** [comment]
Ubuntu 14.04 i386 - I already fixed it - maybe for future users of your script you can replace `apt-get` to `aptitude` because the last one offer some help to fix broken dependencies. Also - thank you for this script.

**Comment by nikole-dunixi** [comment]
Would you mind contributing a pull request? When I originally wrote this script I was using Trusty, but I've changed companies since then and use OSX. If something changes about a dependency I'm not going to know unless people like you bring it to my attention/contribute fixes.

**Comment by castulo** [comment]
@vitaly-zdanevich how did you fix it? I'm getting that problem when running the script:

dpkg: warning: downgrading git from 1:2.14.1-1.1~ppa0~ubuntu14.04.1 to 1:1.9.1-1ubuntu0.6
(Reading database ... 238691 files and directories currently installed.)
Preparing to unpack .../git_1.9.1-1ubuntu0.6_amd64.deb ...
Unpacking git (1:1.9.1-1ubuntu0.6) over (1:2.14.1-1.1~ppa0~ubuntu14.04.1) ...
dpkg: dependency problems prevent configuration of git:
 git depends on git-man (<< 1:1.9.1-.); however:
  Version of git-man on system is 1:2.14.1-1.1~ppa0~ubuntu14.04.1.

dpkg: error processing package git (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 git

**Comment by nikole-dunixi** [comment]
I'm closing this issue, I've got a faux-suite of docker tests and I'm able to build from source on ubuntu 14.04, 16.04, 18.04, 18.10, and 19.04 without un-met dependencies.
