### ISSUE TITLE
Skiptests flag doesnt work 

### ISSUE THREAD

**Issue by chadmandoo** [SonOfLysander/git-openssl-shellscript#8]
sh git.sh -skiptests does not actually skip the tests. Have to remove it manually because the tests fail during the install. Removing the tests it installs correctly.

**Comment by nikole-dunixi** [comment]
Can you tell me what linux distro you were using? I'm curious to see why those tests were failing

**Comment by nikole-dunixi** [comment]
I'm going to close this issue, because I can't replicate this in any of my docker tests. I have recently made updates to this script, perhaps the most recent iteration fixes your issue?

If you have issues still feel free to open a new issue 🙂
